version: '3'

services:
  ghost:
    container_name: ghost
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - db
    environment:
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
    networks:
      - my-network

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - my-network

volumes:
  dbdata:

networks:
  my-network: