version: '3'

services:
  ghost:
    container_name: ghost
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - db
        # condition: service_healthy
    environment:
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    # interval: 1m30s
    # timeout: 20s
    # retries: 10
    # start_period: 30s
